DoctorWkt/pdp7-unix

scans/bc.s
scans/bi.s
scans/bl.s
scans/ind.b
scans/lease.b

My first go at transcribing from the scanned printouts.
They will definitely need to be reviewed for errors!

Transcribed five files

---

scans/cat.s
scans/check.s
scans/chown.s

Please take a look and if they look good, merge.

changes based on scan compare

---

src/sys/s1.s
src/sys/s2.s
src/sys/s3.s
src/sys/s7.s
src/sys/s8.s

noticed "exit" call falls into "rmes" call!!!

sys comments for rmes/smes calls, process table (user list) words

---

build/unixv0.simh

Add comments, commented out commands for Phil's simulation of GRAPHICS-2 

---

scans/ttt1.s
scans/ttt2.s
scans/un.s

I opted to add the suggested pagination comments.

fix typos and add pagination comments to ttt{1,2}.s and un.s

---

scans/ttt1.s
scans/ttt2.s
scans/un.s

Fixes one of the errors mentioned in issue #85 in addition to a number of errors in ttt{1,2}.s.

fix some compilation errors in ttt{1,2}.s and un.s

---

scans/README.md

I had not noticed the sorting order in `scans/README.md`. The subsequent merge where this was fixed then created duplicate entries. Here I remove those and place `ls.s` at the correct location.

Remove duplicate entries in scans/README.md.

---

scans/fop.s

Same corrections as previous cancelled request.

minor corrections to fop.s

---

scans/adm.s
scans/ald.s
scans/apr.s
scans/as.s
scans/cas.s
scans/psych.s
scans/t2.s
scans/t7.s
src/cmd/adm.s
src/cmd/apr.s
src/cmd/as.s

Relying on the assembler to tease out some typos seems to pay off.

Fix typos in multiple files.

---

src/cmd/check.s

Fix typos in check.s after review comment

---

src/cmd/salv.s

Unfortunately I have do to another pull request for the review comments since the original pull request was fixed before the review comments were addressed. At least the issues get fixed. :)

Fix typos in salv.s after review comment

---

misc/cas_syntax.txt

Where is an appropriate place to document the input and output formats for the cas program?

cas input and output formats

---

README.md

readded ln dd ken . link for curdir

---

scans/README.md

edited scans/Readme so that op.s pages were on a single line

moved op.s pages onto single line

---

src/cmd/dskio.s

Please review carefully as this is my first attempt at understand PDP-7 assembler. :)

Attempt to describe purpose of source code in dskio.s

---

src/cmd/dsksav.s

Please review carefully as this is my first attempt at understand PDP-7 assembler. :)

Attempt to describe purpose of source code in dsksav.s

---

src/cmd/dskres.s

Please review carefully as this is my first attempt at understand PDP-7 assembler. :)

Attempt to describe purpose of source code in dskres.s

---

misc/cas_syntax.txt

Correct details about input/output formats and provide more
thorough description of character example.

Improve description of cas input/output formats.

---

.travis.yml

install perl module libdatetime-perl

---

src/cmd/t1.s
src/cmd/t2.s
src/cmd/t3.s
src/cmd/t4.s
src/cmd/t5.s
src/cmd/t6.s
src/cmd/t7.s

first part of an effort to revive TMG

t[1-7].s: annotate TMG sources (all start with one or more tabs and ")

---

src/cmd/st1.s
src/cmd/st2.s
src/cmd/st3.s
src/cmd/st4.s
src/cmd/st5.s
src/cmd/st6.s
src/cmd/st7.s

I have been working on porting Space Travel to C, and in the process annotated the assembly code. The C port is available [here](https://github.com/mohd-akram/st).

Annotate st
